# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'ajite' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  use_modular_headers!
  # Pods for ajite
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'GoogleSignIn', '~> 5.0'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  target 'ajiteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ajiteUITests' do
    # Pods for testing
  end

end
